package com.hived.pojo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "hivd")
public class CommentsPojo {

	private String PK;
	private String SK;
	private String entityType;
	private String commentId;
	private String commentsText;
	private String actionType;
	private String creationDate;
	private String productId;

	@DynamoDBHashKey(attributeName = "PK")
	@DynamoDBAutoGeneratedKey
	public String getPK() {
		return PK;
	}

	public void setPK(String PK) {
		this.PK = PK;
	}

	@DynamoDBRangeKey(attributeName = "SK")
	public String getSK() {
		return SK;
	}

	public void setSK(String SK) {
		this.SK = SK;
	}

	public String getEntityType() {
		return entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	public String getCommentId() {
		return commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	public String getCommentsText() {
		return commentsText;
	}

	public void setCommentsText(String commentsText) {
		this.commentsText = commentsText;
	}

	public String getActionType() {
		return actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	public String getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

}
