package com.hived.pojo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "hivd")
public class FriendshipPojo {

	private String PK;
	private String SK;
	private String entityType;
	private String friendshipId;
	private String followingUser;
	private String followedUser;
	private String creationDate;

	@DynamoDBHashKey(attributeName = "PK")
	@DynamoDBAutoGeneratedKey
	public String getPK() {
		return PK;
	}

	public void setPK(String PK) {
		this.PK = PK;
	}

	@DynamoDBRangeKey(attributeName = "SK")
	public String getSK() {
		return SK;
	}

	public void setSK(String SK) {
		this.SK = SK;
	}
	
	public String getEntityType() {
		return entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	public String getFriendshipId() {
		return friendshipId;
	}

	public void setFriendshipId(String friendshipId) {
		this.friendshipId = friendshipId;
	}

	public String getFollowingUser() {
		return followingUser;
	}

	public void setFollowingUser(String followingUser) {
		this.followingUser = followingUser;
	}

	public String getFollowedUser() {
		return followedUser;
	}

	public void setFollowedUser(String followedUser) {
		this.followedUser = followedUser;
	}

	public String getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}
}
