package com.hived.pojo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "hiveds")
public class FriendshipPojo {

	private String PK;
	private String SK;
	private String entityType;
	private Integer friendshipId;
	private Integer followingUser;
	private Integer followedUser;
	private String creationDate;

	@DynamoDBHashKey(attributeName = "PK")
	@DynamoDBAutoGeneratedKey
	public String getPK() {
		return PK;
	}

	public void setPK(String PK) {
		this.PK = PK;
	}

	@DynamoDBRangeKey(attributeName = "SK")
	public String getSK() {
		return SK;
	}

	public void setSK(String SK) {
		this.SK = SK;
	}
	
	public String getEntityType() {
		return entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	public Integer getFriendshipId() {
		return friendshipId;
	}

	public void setFriendshipId(Integer friendshipId) {
		this.friendshipId = friendshipId;
	}

	public Integer getFollowingUser() {
		return followingUser;
	}

	public void setFollowingUser(Integer followingUser) {
		this.followingUser = followingUser;
	}

	public Integer getFollowedUser() {
		return followedUser;
	}

	public void setFollowedUser(Integer followedUser) {
		this.followedUser = followedUser;
	}

	public String getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

}
